scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']
      - targets: ['otel-collector:8888']
  - job_name: 'kafkaproducer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafkaproducer:8080']
  - job_name: 'kafkaproducer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['kafkaproducer:8090']      